name = "dns-syn"
main = "src/index.js"
compatibility_date = "2023-05-26"

# 触发器配置
# 默认每6小时执行一次同步
[triggers]
crons = ["0 */6 * * *"]

# KV存储配置示例（二选一：KV或D1）
# 替换为你自己的命名空间ID
[[kv_namespaces]]
binding = "KV"
id = "66588457631a43eda90225ebd193c70b"
preview_id = "2e672673d3624255a6a62ed5a7680886"  # 开发环境使用

# D1数据库配置示例（二选一：KV或D1）
# 替换为你自己的数据库ID
# [[d1_databases]]
# binding = "DB"
# database_name = "dns_sync_db"
# database_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# 环境变量配置
[vars]
USERNAME = "admin"
JWT_SECRET = "your-jwt-secret-change-in-production"
CRON = "0 */6 * * *"

# 敏感信息使用Secrets，不要在此处设置
# 使用命令设置Secrets: npx wrangler secret put PASSWORD

# 开发环境配置
[dev]
port = 8787
local_protocol = "http" 